### ISSUE TITLE
scraper failing - IndexError: list index out of range

### ISSUE THREAD

**Issue by mx1010** [harismuneer/Ultimate-Facebook-Scraper#119]
Hey all 👋 

Has anyone encountered this issue ? Trying to figure out if I have something configured wrong or if it is a potential bug.

```
(venv) $ python scraper/scraper.py
{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}

Starting Scraping...

Looking for [chromedriver 81.0.4044.138 mac64] driver in cache
File found in cache by path [/Users/mx1010/.wdm/drivers/chromedriver/81.0.4044.138/mac64/chromedriver]
Traceback (most recent call last):
  File "scraper/scraper.py", line 902, in <module>
    scraper()
  File "scraper/scraper.py", line 810, in scraper
    scrap_profile()
  File "scraper/scraper.py", line 537, in scrap_profile
    user_id = create_original_link(url)
  File "scraper/scraper.py", line 506, in create_original_link
    facebook_https_prefix + facebook_link_body + ((url.split("="))[1])
IndexError: list index out of range
(venv) $
```

**Comment by Liciliy** [comment]
Hi,
How does your input URL looks like?
/V

**Comment by Deepi-cyber** [comment]
Errror something like this:
{'uploaded_photos': True, 'friends_photos': True, 'friends_small_size': True, 'photos_small_size': True, 'total_scrolls': 2500, 'scroll_time': 8}
Traceback (most recent call last):
  File "scraper/scraper.py", line 903, in <module>
    scraper()
  File "scraper/scraper.py", line 793, in scraper
    cfg = yaml.safe_load(stream=ymlfile)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "credentials.yaml", line 1, column 30
