### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by VikashKothary** [harismuneer/Ultimate-Facebook-Scraper#122]
**Describe the bug**
No module named 'utils' when using the module from pypi. You should change line https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/48483a4019ddd9d17bc6de9bc1ae57ad83408324/scraper/scraper.py#L6 into `from scraper import utils`

**To Reproduce**
1. `pip install git+https://github.com/harismuneer/Ultimate-Facebook-Scraper#v2.0`
2. `ultimate-facebook-scraper`

**Expected behavior**
It should run the scraper. But throws an error

**Screenshots or command output**
```
Traceback (most recent call last):
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/.venv/bin/ultimate-facebook-scraper", line 11, in <module>
    load_entry_point('ultimate-facebook-scraper', 'console_scripts', 'ultimate-facebook-scraper')()
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/project-8/src/ultimate_facebook_scraper/scraper/__main__.py", line 1, in <module>
    from .scraper import scraper
  File "/Users/vikash/Programming/training-udacity/udacity-data-engineering/project-8/src/ultimate_facebook_scraper/scraper/scraper.py", line 6, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python version: 3.7.6

**Additional context**

**Comment by aymather** [comment]
Getting this same bug. Tried using `from scraper import utils` and now I'm getting this error:

```
ImportError: cannot import name 'utils' from partially initialized module 'scraper' (most likely due to a circular import) (~/Desktop/Projects/Ultimate-Facebook-Scraper/scraper/scraper.py)
```

I'm not a python expert so this might be a simple fix?

**Comment by jessanKhan** [comment]
change the name of that utils.py to any other name. and find and replace all "utils" in scrapper.py
Hope Your problem will be solved. @aymather @VikashKothary 

it is giving error because there is also a package called "utils"

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
