### ISSUE TITLE
Followers of Groups

### ISSUE THREAD

**Issue by adastra21** [harismuneer/Ultimate-Facebook-Scraper#136]
Is it possible to also scrap followers of public groups? I'm working on a research project to understand the followers of certain public groups, and was curious if this is in the pipeline or/and there's a workaround to get followers for groups.

**Comment by Rahulsunny11** [comment]
even I am working on this.. i want to get followers of public groups and pages

**Comment by Deepi-cyber** [comment]
i am not able to open chrome web page and some class type error coming......will anyone please help?

**Comment by adastra21** [comment]
What's your error? Please ensure that you have installed all the dependencies (https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/v2.0/requirements.txt).

**Comment by Deepi-cyber** [comment]
let me share my error with you and i have installed all the dependencies
Traceback (most recent call last):
  File "scraper/scraper.py", line 904, in <module>
    scraper()
  File "scraper/scraper.py", line 794, in scraper
    cfg = yaml.safe_load(stream=ymlfile)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "credentials.yaml", line 1, column 30

**Comment by Rahulsunny11** [comment]
This is because there is an extra character ("\t"  ) in your credentials.yaml..please edit your credentials.yaml file and run it

**Comment by Deepi-cyber** [comment]
Thank you it worked...but i want to search more than profile like i am able to give photos and videos and the scraper will search that in facebook..any suggestion for that

**Comment by adastra21** [comment]
I don't think this scraper is built for that kind of scraping, so you might want to consider another scraper, or build something specific.
