### ISSUE TITLE
How to start on windows env. i got this error.

### ISSUE THREAD

**Issue by tineebel** [harismuneer/Ultimate-Facebook-Scraper#179]
C:\Ultimate-Facebook-Scraper-2.0>ultimate-facebook-scraper
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\ultimate-facebook-scraper-script.py", line 11, in <module>
    load_entry_point('ultimate-facebook-scraper', 'console_scripts', 'ultimate-facebook-scraper')()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\ultimate-facebook-scraper-2.0\ultimate-facebook-scraper\scraper\__main__.py", line 1, in <module>
    from .scraper import scraper
  File "c:\ultimate-facebook-scraper-2.0\ultimate-facebook-scraper\scraper\scraper.py", line 6, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

C:\Ultimate-Facebook-Scraper-2.0>

**Comment by DanielBuzkov** [comment]
From the UFS dir execute:
`python scraper/scraper.py`
That should do it

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
