### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Rootzilla** [harismuneer/Ultimate-Facebook-Scraper#184]
```
rootz@kali:~/Masaüstü/Ultimate-Facebook-Scraper$ ultimate-facebook-scraper
Traceback (most recent call last):
  File "/usr/local/bin/ultimate-facebook-scraper", line 33, in <module>
    sys.exit(load_entry_point('ultimate-facebook-scraper', 'console_scripts', 'ultimate-facebook-scraper')())
  File "/usr/local/bin/ultimate-facebook-scraper", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
![Screenshot_8](https://user-images.githubusercontent.com/56687483/97786064-ff3cb380-1bb9-11eb-8826-35a5ecfa677d.png)

    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rootz/Masaüstü/Ultimate-Facebook-Scraper/scraper/__main__.py", line 1, in <module>
    from .scraper import scraper
  File "/home/rootz/Masaüstü/Ultimate-Facebook-Scraper/scraper/scraper.py", line 6, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
rootz@kali:~/Masaüstü/Ultimate-Facebook-Scraper$
```

**Comment by NoelJacob** [comment]
+1

**Comment by elig0n** [comment]
temporarily you can use 'python scraper/scraper.py' to run it

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_

<hr>

^ This is issue is also fixed in the new version. So spread the word and support the tool.
