### ISSUE TITLE
Can Not scrap friends and downlad images

### ISSUE THREAD

**Issue by exblopz** [harismuneer/Ultimate-Facebook-Scraper#82]
I run the script and then have this error:

```
DevTools listening on ws://127.0.0.1:56056/devtools/browser/920aa778-fa5a-4609-a23d-267bb7024697

Scraping: https://www.facebook.com/romadhoni
----------------------------------------
Friends..
Friends Done!
----------------------------------------
Photos..
Scraping Links..
Photos Done!
----------------------------------------
Videos:
Videos Done!
----------------------------------------
About:
About Section Done!
----------------------------------------
Posts:
Posts(Statuses) Done!
----------------------------------------

Process Completed.
Traceback (most recent call last):
  File "c:\users\archangle\documents\work\ultimate-facebook-scraper-2.0\venv\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'scraper.__main__' has no attribute 'scraper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ARCHANGLE\Documents\WORK\Ultimate-Facebook-Scraper-2.0\venv\Scripts\ultimate-facebook-scraper-script.py", line 11, in <module>
    load_entry_point('ultimate-facebook-scraper', 'console_scripts', 'ultimate-facebook-scraper')()
  File "c:\users\archangle\documents\work\ultimate-facebook-scraper-2.0\venv\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\archangle\documents\work\ultimate-facebook-scraper-2.0\venv\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\archangle\documents\work\ultimate-facebook-scraper-2.0\venv\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\archangle\documents\work\ultimate-facebook-scraper-2.0\venv\lib\site-packages\pkg_resources\__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'scraper.__main__' has no attribute 'scraper'

```
And also in the example I saw the script creating directory, but in my trial it doesn't create anything. Why? And there is no signed error of creating directory.

By the way, I'm using windows 10 and python 3

**Comment by malek-h** [comment]
Hello 

I have the same problem 
is this been solved please 

Thank you

**Comment by haunttpd00207** [comment]
Only About information was scrap, anything else did not.

**Comment by LuanBaviloni** [comment]
**Solution**

I discovered why it's not working for some people. In other languages than English, the title of sections are different. The script uses theses titles to check if the pages was loaded correctly. **That's the problem!**

Change your _scraper/scraper.py_ and replace the `scan_list` variables with the correct value for your language.

**OR**

Change your Facebook language to English.

**Comment by malek-h** [comment]
Hi 

thank you it was resolve for me

**Comment by RubeVi17** [comment]
> **Solution**
> 
> I discovered why it's not working for some people. In other languages than English, the title of sections are different. The script uses theses titles to check if the pages was loaded correctly. **That's the problem!**
> 
> Change your _scraper/scraper.py_ and replace the `scan_list` variables with the correct value for your language.
> 
> **OR**
> 
> Change your Facebook language to English.

worked for me!

**Comment by harismuneer** [comment]
@LuanBaviloni thanks for the tweak, will include that in the readme file 👍
